# Generated by Django 3.2.12 on 2022-03-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=256)),
                ('Address', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Reason', models.TextField()),
                ('Call_back', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
            ],
        ),
    ]
